activation: Tanh
cell_channels: 9
emb_dim: 12
emb_hidden: 1024
factor: 0.7
hparams:
  activation: Tanh
  cell_channels: 9
  emb_dim: 12
  emb_hidden: 1024
  factor: 0.7
  input_dir: datasets/feature_store/quickstart_example_1GeV
  knn: 50
  lr: 0.001
  margin: 0.1
  max_epochs: 30
  nb_layer: 4
  output_dir: datasets/quickstart_metric_learning_processed
  patience: 4
  points_per_batch: 100000
  pt_background_cut: 0.0
  pt_signal_cut: 0.0
  r_test: 0.1
  r_train: 0.1
  r_val: 0.1
  randomisation: 2
  regime: &id001
  - rp
  - hnm
  - norm
  spatial_channels: 3
  train_split: &id002
  - 80
  - 3
  - 3
  true_edges: modulewise_true_edges
  warmup: 8
  weight: 2
input_dir: datasets/feature_store/quickstart_example_1GeV
knn: 50
lr: 0.001
margin: 0.1
max_epochs: 30
nb_layer: 4
output_dir: datasets/quickstart_metric_learning_processed
patience: 4
points_per_batch: 100000
pt_background_cut: 0.0
pt_signal_cut: 0.0
r_test: 0.1
r_train: 0.1
r_val: 0.1
randomisation: 2
regime: *id001
spatial_channels: 3
train_split: *id002
true_edges: modulewise_true_edges
warmup: 8
weight: 2
