aggregation: sum_max
cell_channels: 0
datatype_names:
- train
- val
- test
datatype_split:
- 71
- 8
- 8
edge_cut: 0.0
factor: 0.7
hidden: 128
hidden_activation: SiLU
input_dir: datasets/quickstart_metric_learning_processed
layernorm: true
lr: 0.002
mask_background: true
max_epochs: 2
n_graph_iters: 6
nb_edge_layer: 3
nb_node_layer: 3
noise: false
output_dir: datasets/quickstart_gnn_processed
patience: 8
pt_background_min: 0.0
pt_signal_min: 0.0
spatial_channels: 3
weight: 2
